version: '2'
services:
  app:
    build: .
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - ./plugins:/app/plugins
    - ./public:/app/public
    - ./ecosystem.json:/app/ecosystem.json
    - ./index.js:/app/index.js
    depends_on:
    - redis
    environment:
#    - LETSENCRYPT_DOMAIN=localhost
    - NODE_ENV=development
    - REDIS_PORT_6379_ADDR=redis
  redis:
    image: redis:3
